import { StickerAlbum, Achievement } from '@/lib/types';

export const initialStickerAlbum: StickerAlbum = {
  pages: [
    {
      id: 'page_daily',
      name: 'Daily Routine',
      emoji: '🌅',
      reward: '50 coins',
      completed: false,
      stickers: [
        { id: 'sticker_first_wake', name: 'Early Bird', emoji: '🐦', earned: false, earnedAt: null },
        { id: 'sticker_brush_teeth', name: 'Sparkle Smile', emoji: '😁', earned: false, earnedAt: null },
        { id: 'sticker_first_meal', name: 'Chef Emersyn', emoji: '👩‍🍳', earned: false, earnedAt: null },
        { id: 'sticker_clean_room', name: 'Tidy Room', emoji: '🧹', earned: false, earnedAt: null },
        { id: 'sticker_bath_time', name: 'Squeaky Clean', emoji: '🛁', earned: false, earnedAt: null },
        { id: 'sticker_bedtime', name: 'Sweet Dreams', emoji: '🌙', earned: false, earnedAt: null },
      ],
    },
    {
      id: 'page_school',
      name: 'School Star',
      emoji: '🏫',
      reward: '75 coins',
      completed: false,
      stickers: [
        { id: 'sticker_first_school', name: 'First Day!', emoji: '🎒', earned: false, earnedAt: null },
        { id: 'sticker_math_star', name: 'Math Whiz', emoji: '🔢', earned: false, earnedAt: null },
        { id: 'sticker_reading', name: 'Book Worm', emoji: '📚', earned: false, earnedAt: null },
        { id: 'sticker_art_class', name: 'Little Artist', emoji: '🎨', earned: false, earnedAt: null },
        { id: 'sticker_homework_5', name: 'Homework Hero', emoji: '✏️', earned: false, earnedAt: null },
        { id: 'sticker_perfect_score', name: 'Perfect Score!', emoji: '💯', earned: false, earnedAt: null },
      ],
    },
    {
      id: 'page_cooking',
      name: 'Kitchen Queen',
      emoji: '👩‍🍳',
      reward: '100 coins',
      completed: false,
      stickers: [
        { id: 'sticker_first_cook', name: 'First Recipe', emoji: '🍳', earned: false, earnedAt: null },
        { id: 'sticker_pizza_master', name: 'Pizza Master', emoji: '🍕', earned: false, earnedAt: null },
        { id: 'sticker_burger_stack', name: 'Burger Builder', emoji: '🍔', earned: false, earnedAt: null },
        { id: 'sticker_dessert_queen', name: 'Dessert Queen', emoji: '🧁', earned: false, earnedAt: null },
        { id: 'sticker_10_recipes', name: '10 Recipes!', emoji: '📖', earned: false, earnedAt: null },
        { id: 'sticker_all_recipes', name: 'Master Chef', emoji: '👑', earned: false, earnedAt: null },
      ],
    },
    {
      id: 'page_park',
      name: 'Park Explorer',
      emoji: '🏞️',
      reward: '75 coins',
      completed: false,
      stickers: [
        { id: 'sticker_first_park', name: 'Park Visit', emoji: '🌳', earned: false, earnedAt: null },
        { id: 'sticker_scooty_ride', name: 'Scooty Star', emoji: '🛴', earned: false, earnedAt: null },
        { id: 'sticker_trampoline', name: 'Bounce King', emoji: '🤸', earned: false, earnedAt: null },
        { id: 'sticker_skating', name: 'Skate Pro', emoji: '⛸️', earned: false, earnedAt: null },
        { id: 'sticker_slide_fun', name: 'Slide Champion', emoji: '🎢', earned: false, earnedAt: null },
        { id: 'sticker_park_10', name: 'Park Regular', emoji: '🏅', earned: false, earnedAt: null },
      ],
    },
    {
      id: 'page_arcade',
      name: 'Arcade Champion',
      emoji: '🕹️',
      reward: '150 coins',
      completed: false,
      stickers: [
        { id: 'sticker_first_game', name: 'Player One', emoji: '🎮', earned: false, earnedAt: null },
        { id: 'sticker_runner_1000', name: 'Speed Demon', emoji: '💨', earned: false, earnedAt: null },
        { id: 'sticker_dance_star', name: 'Dance Star', emoji: '💃', earned: false, earnedAt: null },
        { id: 'sticker_karate_belt', name: 'Belt Up!', emoji: '🥋', earned: false, earnedAt: null },
        { id: 'sticker_high_score', name: 'High Score!', emoji: '🏆', earned: false, earnedAt: null },
        { id: 'sticker_arcade_master', name: 'Arcade Master', emoji: '👑', earned: false, earnedAt: null },
      ],
    },
    {
      id: 'page_shopping',
      name: 'Fashion Queen',
      emoji: '🛍️',
      reward: '100 coins',
      completed: false,
      stickers: [
        { id: 'sticker_first_purchase', name: 'First Buy!', emoji: '🛒', earned: false, earnedAt: null },
        { id: 'sticker_10_items', name: '10 Items!', emoji: '🎁', earned: false, earnedAt: null },
        { id: 'sticker_full_outfit', name: 'Full Outfit', emoji: '👗', earned: false, earnedAt: null },
        { id: 'sticker_unicorn_collection', name: 'Unicorn Collector', emoji: '🦄', earned: false, earnedAt: null },
        { id: 'sticker_room_decor', name: 'Room Designer', emoji: '🏠', earned: false, earnedAt: null },
        { id: 'sticker_50_items', name: 'Shopaholic!', emoji: '💎', earned: false, earnedAt: null },
      ],
    },
    {
      id: 'page_brave',
      name: 'Brave Badge',
      emoji: '🦸',
      reward: '100 coins + Brave Teddy',
      completed: false,
      stickers: [
        { id: 'sticker_first_bug', name: 'First Bug!', emoji: '🐛', earned: false, earnedAt: null },
        { id: 'sticker_close_window', name: 'Window Guard', emoji: '🪟', earned: false, earnedAt: null },
        { id: 'sticker_fan_hero', name: 'Fan Hero', emoji: '🌀', earned: false, earnedAt: null },
        { id: 'sticker_net_master', name: 'Net Master', emoji: '🥅', earned: false, earnedAt: null },
        { id: 'sticker_bug_5', name: '5 Bugs Handled', emoji: '💪', earned: false, earnedAt: null },
        { id: 'sticker_bug_brave', name: 'Super Brave!', emoji: '🦸', earned: false, earnedAt: null },
      ],
    },
    {
      id: 'page_weekend',
      name: 'Weekend Star',
      emoji: '🌟',
      reward: '150 coins',
      completed: false,
      stickers: [
        { id: 'sticker_first_reel', name: 'First Reel!', emoji: '🎬', earned: false, earnedAt: null },
        { id: 'sticker_makeover', name: 'Makeover Magic', emoji: '💄', earned: false, earnedAt: null },
        { id: 'sticker_100_likes', name: '100 Likes!', emoji: '❤️', earned: false, earnedAt: null },
        { id: 'sticker_popular', name: 'Popular Star', emoji: '🌟', earned: false, earnedAt: null },
        { id: 'sticker_5_reels', name: '5 Reels Made', emoji: '📱', earned: false, earnedAt: null },
        { id: 'sticker_weekend_master', name: 'Weekend Master', emoji: '👑', earned: false, earnedAt: null },
      ],
    },
  ],
};

export const allAchievements: Achievement[] = [
  { id: 'ach_first_day', name: 'Day One!', emoji: '🎉', description: 'Complete your first full day', earned: false, earnedAt: null },
  { id: 'ach_7_days', name: 'Week Warrior', emoji: '📅', description: 'Play for 7 days', earned: false, earnedAt: null },
  { id: 'ach_30_days', name: 'Monthly Star', emoji: '🌟', description: 'Play for 30 days', earned: false, earnedAt: null },
  { id: 'ach_100_coins', name: 'Coin Collector', emoji: '💰', description: 'Earn 100 coins total', earned: false, earnedAt: null },
  { id: 'ach_500_coins', name: 'Money Bags', emoji: '💎', description: 'Earn 500 coins total', earned: false, earnedAt: null },
  { id: 'ach_1000_coins', name: 'Coin Tycoon', emoji: '👑', description: 'Earn 1000 coins total', earned: false, earnedAt: null },
  { id: 'ach_first_recipe', name: 'First Recipe', emoji: '🍳', description: 'Cook your first recipe', earned: false, earnedAt: null },
  { id: 'ach_all_recipes', name: 'Master Chef', emoji: '👩‍🍳', description: 'Unlock all recipes', earned: false, earnedAt: null },
  { id: 'ach_first_outfit', name: 'Fashionista', emoji: '👗', description: 'Buy your first outfit', earned: false, earnedAt: null },
  { id: 'ach_full_wardrobe', name: 'Full Wardrobe', emoji: '👗', description: 'Own 20 clothing items', earned: false, earnedAt: null },
  { id: 'ach_runner_1000', name: 'Speed Racer', emoji: '🏎️', description: 'Score 1000 in Scooty Dash', earned: false, earnedAt: null },
  { id: 'ach_dance_perfect', name: 'Dance Perfect', emoji: '💃', description: 'Get a perfect dance score', earned: false, earnedAt: null },
  { id: 'ach_karate_black', name: 'Black Belt', emoji: '🥋', description: 'Reach black belt in Karate', earned: false, earnedAt: null },
  { id: 'ach_brave_max', name: 'Fearless', emoji: '🦸', description: 'Reach max brave level', earned: false, earnedAt: null },
  { id: 'ach_popular', name: 'Super Popular', emoji: '🌟', description: 'Reach 100 popularity', earned: false, earnedAt: null },
  { id: 'ach_sticker_page', name: 'Page Complete', emoji: '📋', description: 'Complete a sticker page', earned: false, earnedAt: null },
  { id: 'ach_all_stickers', name: 'Sticker Master', emoji: '🏆', description: 'Complete all sticker pages', earned: false, earnedAt: null },
  { id: 'ach_level_5', name: 'Level 5', emoji: '⭐', description: 'Reach level 5', earned: false, earnedAt: null },
  { id: 'ach_level_10', name: 'Level 10', emoji: '🌟', description: 'Reach level 10', earned: false, earnedAt: null },
  { id: 'ach_10_minigames', name: 'Game Lover', emoji: '🎮', description: 'Play 10 mini-games', earned: false, earnedAt: null },
];
