import { Recipe } from '@/lib/types';

export const recipes: Recipe[] = [
  // ========== BREAKFAST ==========
  { id: 'pancakes', name: 'Fluffy Pancakes', emoji: '🥞', category: 'breakfast', ingredients: ['flour', 'egg', 'milk', 'butter'], steps: ['Mix batter', 'Pour on pan', 'Flip!', 'Add syrup'], coinReward: 12, healthBonus: 5, happinessBonus: 10, difficulty: 1, unlockLevel: 1 },
  { id: 'toast_jam', name: 'Toast & Jam', emoji: '🍞', category: 'breakfast', ingredients: ['bread', 'jam'], steps: ['Toast bread', 'Spread jam'], coinReward: 8, healthBonus: 5, happinessBonus: 5, difficulty: 1, unlockLevel: 1 },
  { id: 'cereal_bowl', name: 'Rainbow Cereal', emoji: '🥣', category: 'breakfast', ingredients: ['cereal', 'milk'], steps: ['Pour cereal', 'Add milk', 'Add fruit topping'], coinReward: 6, healthBonus: 5, happinessBonus: 8, difficulty: 1, unlockLevel: 1 },
  { id: 'fruit_smoothie', name: 'Berry Smoothie', emoji: '🥤', category: 'breakfast', ingredients: ['strawberry', 'banana', 'yogurt', 'honey'], steps: ['Add fruits', 'Pour yogurt', 'Blend!', 'Pour into glass'], coinReward: 10, healthBonus: 15, happinessBonus: 8, difficulty: 1, unlockLevel: 2 },
  { id: 'egg_sunny', name: 'Sunny Side Up Egg', emoji: '🍳', category: 'breakfast', ingredients: ['egg', 'butter', 'salt'], steps: ['Crack egg', 'Fry gently', 'Season'], coinReward: 8, healthBonus: 10, happinessBonus: 5, difficulty: 1, unlockLevel: 1 },
  { id: 'waffle_heart', name: 'Heart Waffles', emoji: '🧇', category: 'breakfast', ingredients: ['flour', 'egg', 'milk', 'sugar'], steps: ['Mix batter', 'Pour in waffle iron', 'Cook golden', 'Add toppings'], coinReward: 14, healthBonus: 5, happinessBonus: 12, difficulty: 2, unlockLevel: 3 },

  // ========== LUNCH ==========
  { id: 'pizza_basic', name: 'Cheese Pizza', emoji: '🍕', category: 'lunch', ingredients: ['dough', 'sauce', 'cheese'], steps: ['Roll dough', 'Spread sauce', 'Add cheese', 'Bake!'], coinReward: 15, healthBonus: 5, happinessBonus: 15, difficulty: 1, unlockLevel: 1 },
  { id: 'pizza_veggie', name: 'Veggie Pizza', emoji: '🍕', category: 'lunch', ingredients: ['dough', 'sauce', 'cheese', 'peppers', 'mushrooms'], steps: ['Roll dough', 'Spread sauce', 'Add cheese', 'Add veggies', 'Bake!'], coinReward: 18, healthBonus: 10, happinessBonus: 12, difficulty: 2, unlockLevel: 3 },
  { id: 'pizza_heart', name: 'Heart Pizza', emoji: '💖', category: 'lunch', ingredients: ['dough', 'sauce', 'cheese', 'olives'], steps: ['Shape heart dough', 'Spread sauce', 'Add cheese', 'Decorate with olives', 'Bake!'], coinReward: 20, healthBonus: 5, happinessBonus: 18, difficulty: 2, unlockLevel: 4 },
  { id: 'burger_classic', name: 'Classic Burger', emoji: '🍔', category: 'lunch', ingredients: ['bun', 'patty', 'lettuce', 'tomato', 'cheese'], steps: ['Place bottom bun', 'Add patty', 'Stack lettuce', 'Add tomato', 'Place cheese', 'Top bun!'], coinReward: 15, healthBonus: 5, happinessBonus: 15, difficulty: 1, unlockLevel: 1 },
  { id: 'burger_tower', name: 'Tower Burger', emoji: '🍔', category: 'lunch', ingredients: ['bun', 'patty', 'patty', 'cheese', 'lettuce', 'sauce'], steps: ['Stack double patties', 'Add cheese layers', 'Add veggies', 'Balance the tower!'], coinReward: 22, healthBonus: 3, happinessBonus: 20, difficulty: 3, unlockLevel: 5 },
  { id: 'chicken_bites', name: 'Crispy Chicken Bites', emoji: '🍗', category: 'lunch', ingredients: ['chicken', 'breadcrumbs', 'spices'], steps: ['Coat chicken', 'Roll in crumbs', 'Fry golden', 'Serve with dip'], coinReward: 14, healthBonus: 5, happinessBonus: 14, difficulty: 2, unlockLevel: 2 },
  { id: 'fries_classic', name: 'Golden Fries', emoji: '🍟', category: 'lunch', ingredients: ['potatoes', 'oil', 'salt'], steps: ['Cut potatoes', 'Fry until golden', 'Shake salt'], coinReward: 10, healthBonus: 2, happinessBonus: 12, difficulty: 1, unlockLevel: 1 },
  { id: 'fries_curly', name: 'Curly Fries', emoji: '🍟', category: 'lunch', ingredients: ['potatoes', 'oil', 'spice_mix'], steps: ['Spiral cut', 'Season', 'Fry crispy'], coinReward: 14, healthBonus: 2, happinessBonus: 15, difficulty: 2, unlockLevel: 3 },
  { id: 'sandwich_club', name: 'Club Sandwich', emoji: '🥪', category: 'lunch', ingredients: ['bread', 'chicken', 'lettuce', 'tomato', 'mayo'], steps: ['Toast bread', 'Layer ingredients', 'Cut diagonal', 'Add toothpick flag'], coinReward: 12, healthBonus: 8, happinessBonus: 10, difficulty: 1, unlockLevel: 2 },
  { id: 'pasta_bow', name: 'Bow Tie Pasta', emoji: '🍝', category: 'lunch', ingredients: ['pasta', 'sauce', 'cheese'], steps: ['Boil pasta', 'Make sauce', 'Mix together', 'Sprinkle cheese'], coinReward: 14, healthBonus: 5, happinessBonus: 12, difficulty: 2, unlockLevel: 3 },
  { id: 'rice_emoji', name: 'Emoji Rice Bowl', emoji: '🍚', category: 'lunch', ingredients: ['rice', 'nori', 'veggies'], steps: ['Cook rice', 'Shape into ball', 'Cut nori face', 'Add veggie sides'], coinReward: 16, healthBonus: 10, happinessBonus: 14, difficulty: 2, unlockLevel: 4 },
  { id: 'taco_fun', name: 'Fun Tacos', emoji: '🌮', category: 'lunch', ingredients: ['taco_shell', 'beans', 'cheese', 'salsa', 'lettuce'], steps: ['Warm shell', 'Add beans', 'Sprinkle cheese', 'Top with salsa'], coinReward: 14, healthBonus: 8, happinessBonus: 12, difficulty: 2, unlockLevel: 3 },
  { id: 'wrap_rainbow', name: 'Rainbow Wrap', emoji: '🌯', category: 'lunch', ingredients: ['tortilla', 'chicken', 'peppers', 'carrot', 'lettuce'], steps: ['Lay tortilla', 'Add rainbow layers', 'Roll tightly', 'Cut in half'], coinReward: 16, healthBonus: 12, happinessBonus: 10, difficulty: 2, unlockLevel: 4 },

  // ========== SNACKS ==========
  { id: 'fruit_bowl', name: 'Rainbow Fruit Bowl', emoji: '🍓', category: 'snack', ingredients: ['strawberry', 'banana', 'blueberry', 'kiwi', 'mango'], steps: ['Slice fruits', 'Arrange rainbow', 'Add honey drizzle'], coinReward: 10, healthBonus: 20, happinessBonus: 8, difficulty: 1, unlockLevel: 1 },
  { id: 'popcorn_sweet', name: 'Sweet Popcorn', emoji: '🍿', category: 'snack', ingredients: ['corn', 'butter', 'sugar'], steps: ['Pop corn', 'Melt butter', 'Drizzle & shake'], coinReward: 8, healthBonus: 2, happinessBonus: 10, difficulty: 1, unlockLevel: 1 },
  { id: 'popcorn_chicken', name: 'Popcorn Chicken', emoji: '🍗', category: 'snack', ingredients: ['chicken', 'flour', 'spices'], steps: ['Cut tiny pieces', 'Coat & season', 'Fry crispy'], coinReward: 12, healthBonus: 5, happinessBonus: 12, difficulty: 2, unlockLevel: 2 },
  { id: 'nachos_cheese', name: 'Cheesy Nachos', emoji: '🧀', category: 'snack', ingredients: ['chips', 'cheese', 'salsa'], steps: ['Arrange chips', 'Melt cheese on top', 'Add salsa'], coinReward: 10, healthBonus: 2, happinessBonus: 12, difficulty: 1, unlockLevel: 2 },
  { id: 'trail_mix', name: 'Trail Mix Cup', emoji: '🥜', category: 'snack', ingredients: ['nuts', 'raisins', 'chocolate_chips'], steps: ['Scoop nuts', 'Add raisins', 'Sprinkle chocolate'], coinReward: 8, healthBonus: 10, happinessBonus: 6, difficulty: 1, unlockLevel: 1 },
  { id: 'yogurt_parfait', name: 'Yogurt Parfait', emoji: '🍨', category: 'snack', ingredients: ['yogurt', 'granola', 'berries', 'honey'], steps: ['Layer yogurt', 'Add granola', 'Top with berries', 'Drizzle honey'], coinReward: 12, healthBonus: 15, happinessBonus: 10, difficulty: 1, unlockLevel: 2 },
  { id: 'cheese_crackers', name: 'Cheese & Crackers', emoji: '🧀', category: 'snack', ingredients: ['crackers', 'cheese', 'grapes'], steps: ['Arrange crackers', 'Slice cheese', 'Add grapes'], coinReward: 8, healthBonus: 5, happinessBonus: 6, difficulty: 1, unlockLevel: 1 },

  // ========== DINNER ==========
  { id: 'soup_tomato', name: 'Tomato Soup', emoji: '🍲', category: 'dinner', ingredients: ['tomatoes', 'onion', 'cream', 'herbs'], steps: ['Cook tomatoes', 'Blend smooth', 'Add cream', 'Sprinkle herbs'], coinReward: 12, healthBonus: 12, happinessBonus: 8, difficulty: 2, unlockLevel: 2 },
  { id: 'rice_curry', name: 'Rice & Curry', emoji: '🍛', category: 'dinner', ingredients: ['rice', 'veggies', 'curry_sauce', 'spices'], steps: ['Cook rice', 'Prepare veggies', 'Make curry sauce', 'Serve together'], coinReward: 16, healthBonus: 10, happinessBonus: 12, difficulty: 2, unlockLevel: 3 },
  { id: 'noodle_stir', name: 'Stir Fry Noodles', emoji: '🍜', category: 'dinner', ingredients: ['noodles', 'veggies', 'soy_sauce', 'oil'], steps: ['Cook noodles', 'Stir fry veggies', 'Add sauce', 'Toss together'], coinReward: 14, healthBonus: 8, happinessBonus: 12, difficulty: 2, unlockLevel: 3 },
  { id: 'dinner_plate', name: 'Balanced Dinner Plate', emoji: '🍽️', category: 'dinner', ingredients: ['rice', 'chicken', 'veggies', 'salad'], steps: ['Cook rice', 'Grill chicken', 'Steam veggies', 'Arrange plate'], coinReward: 18, healthBonus: 15, happinessBonus: 10, difficulty: 2, unlockLevel: 4 },
  { id: 'mini_dosa', name: 'Mini Dosa Set', emoji: '🥘', category: 'dinner', ingredients: ['dosa_batter', 'potato', 'chutney', 'sambar'], steps: ['Spread batter thin', 'Cook golden', 'Fill with potato', 'Serve with chutney'], coinReward: 16, healthBonus: 10, happinessBonus: 14, difficulty: 2, unlockLevel: 3 },

  // ========== DESSERTS ==========
  { id: 'candy_assorted', name: 'Candy Box', emoji: '🍬', category: 'dessert', ingredients: ['candy_mix'], steps: ['Open box', 'Arrange candies', 'Pick your favorites!'], coinReward: 8, healthBonus: 0, happinessBonus: 15, difficulty: 1, unlockLevel: 1 },
  { id: 'cotton_candy', name: 'Cotton Candy', emoji: '🍭', category: 'dessert', ingredients: ['sugar', 'food_coloring'], steps: ['Spin sugar', 'Wrap around stick', 'Make it big!'], coinReward: 10, healthBonus: 0, happinessBonus: 18, difficulty: 1, unlockLevel: 1 },
  { id: 'ice_cream_sundae', name: 'Ice Cream Sundae', emoji: '🍨', category: 'dessert', ingredients: ['ice_cream', 'chocolate_sauce', 'sprinkles', 'cherry'], steps: ['Scoop ice cream', 'Drizzle chocolate', 'Add sprinkles', 'Place cherry on top!'], coinReward: 14, healthBonus: 0, happinessBonus: 20, difficulty: 1, unlockLevel: 2 },
  { id: 'cupcake_rainbow', name: 'Rainbow Cupcake', emoji: '🧁', category: 'dessert', ingredients: ['flour', 'sugar', 'eggs', 'frosting', 'sprinkles'], steps: ['Mix batter colors', 'Layer in cup', 'Bake', 'Frost & decorate'], coinReward: 16, healthBonus: 0, happinessBonus: 18, difficulty: 2, unlockLevel: 3 },
  { id: 'cookie_stars', name: 'Star Cookies', emoji: '🍪', category: 'dessert', ingredients: ['flour', 'butter', 'sugar', 'vanilla'], steps: ['Mix dough', 'Cut star shapes', 'Bake golden', 'Decorate with icing'], coinReward: 12, healthBonus: 0, happinessBonus: 14, difficulty: 2, unlockLevel: 2 },
  { id: 'cake_birthday', name: 'Mini Birthday Cake', emoji: '🎂', category: 'dessert', ingredients: ['flour', 'sugar', 'eggs', 'frosting', 'sprinkles', 'candles'], steps: ['Bake layers', 'Stack & frost', 'Add sprinkles', 'Place candles', 'Make a wish!'], coinReward: 25, healthBonus: 0, happinessBonus: 25, difficulty: 3, unlockLevel: 5 },
  { id: 'chocolate_truffle', name: 'Chocolate Truffles', emoji: '🍫', category: 'dessert', ingredients: ['chocolate', 'cream', 'cocoa_powder'], steps: ['Melt chocolate', 'Mix with cream', 'Roll balls', 'Dust with cocoa'], coinReward: 14, healthBonus: 0, happinessBonus: 16, difficulty: 2, unlockLevel: 3 },
  { id: 'donut_sprinkle', name: 'Sprinkle Donuts', emoji: '🍩', category: 'dessert', ingredients: ['dough', 'glaze', 'sprinkles'], steps: ['Shape donuts', 'Fry golden', 'Dip in glaze', 'Cover in sprinkles!'], coinReward: 12, healthBonus: 0, happinessBonus: 16, difficulty: 2, unlockLevel: 2 },
  { id: 'jelly_cups', name: 'Rainbow Jelly Cups', emoji: '🍮', category: 'dessert', ingredients: ['jelly_mix', 'fruit', 'cream'], steps: ['Layer jelly colors', 'Chill', 'Add fruit', 'Top with cream'], coinReward: 10, healthBonus: 2, happinessBonus: 14, difficulty: 2, unlockLevel: 3 },
  { id: 'lollipop_swirl', name: 'Swirl Lollipop', emoji: '🍭', category: 'dessert', ingredients: ['sugar', 'food_coloring', 'stick'], steps: ['Heat sugar', 'Add colors', 'Swirl together', 'Shape on stick'], coinReward: 8, healthBonus: 0, happinessBonus: 12, difficulty: 1, unlockLevel: 1 },

  // ========== DRINKS ==========
  { id: 'lemonade', name: 'Pink Lemonade', emoji: '🍋', category: 'drink', ingredients: ['lemons', 'sugar', 'water', 'pink_color'], steps: ['Squeeze lemons', 'Mix with sugar water', 'Add pink!', 'Pour over ice'], coinReward: 8, healthBonus: 5, happinessBonus: 8, difficulty: 1, unlockLevel: 1 },
  { id: 'hot_chocolate', name: 'Hot Chocolate', emoji: '☕', category: 'drink', ingredients: ['chocolate', 'milk', 'marshmallows'], steps: ['Heat milk', 'Stir in chocolate', 'Add marshmallows'], coinReward: 10, healthBonus: 2, happinessBonus: 12, difficulty: 1, unlockLevel: 1 },
  { id: 'mango_lassi', name: 'Mango Lassi', emoji: '🥭', category: 'drink', ingredients: ['mango', 'yogurt', 'sugar', 'cardamom'], steps: ['Blend mango', 'Add yogurt', 'Sweeten', 'Pour & serve'], coinReward: 10, healthBonus: 8, happinessBonus: 10, difficulty: 1, unlockLevel: 2 },
  { id: 'milkshake_strawberry', name: 'Strawberry Milkshake', emoji: '🍓', category: 'drink', ingredients: ['strawberries', 'ice_cream', 'milk'], steps: ['Add strawberries', 'Scoop ice cream', 'Blend!', 'Top with whipped cream'], coinReward: 12, healthBonus: 3, happinessBonus: 14, difficulty: 1, unlockLevel: 2 },
  { id: 'juice_rainbow', name: 'Rainbow Juice', emoji: '🌈', category: 'drink', ingredients: ['orange', 'apple', 'grape', 'mango'], steps: ['Juice each fruit', 'Layer carefully', 'Rainbow effect!'], coinReward: 14, healthBonus: 15, happinessBonus: 10, difficulty: 2, unlockLevel: 3 },
];

export const getRecipeById = (id: string): Recipe | undefined =>
  recipes.find((r) => r.id === id);

export const getRecipesByCategory = (category: Recipe['category']): Recipe[] =>
  recipes.filter((r) => r.category === category);
